#!/bin/sh

#DEBHELPER#
# copied from ttf-bitstream-vera package

if [ "$1" = configure ] && [ -x /usr/bin/fc-cache ]; then
	echo -n "Regenerating fonts cache... "

	HOME=/root fc-cache -f -v 1>/var/log/fontconfig.log 2>&1
	if [ "$?" -eq 0 ]; then
		echo "done."
	else
		echo "failed; see /var/log/fontconfig.log for more information."
		exit 1
	fi
fi
